app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('studentCircle.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

app/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


class UserManager(BaseUserManager):
    """ Managers for user"""

    def create_user(self, username, email, password=None, **extra_field):
        """ create, save and return new user. """
        if not email:
            raise ValueError('Email is required for signup process')

        user = self.model(
            username=username,
            email=self.normalize_email(
                email), **extra_field)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email,  password=None):
        """ create, save and return super user. """
        user = self.create_user(
            username=username, email=email, password=password)
        user.is_active = True
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username = models.CharField(max_length=20, unique=True)
    email = models.EmailField(max_length=50, unique=True)
    is_room_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return True


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50, null=True)
    profile_picture = models.ImageField(
        upload_to='core/pofile_pictures', default="avatar.svg", null=True)
    city = models.CharField(max_length=200, null=True)
    bio = models.TextField(max_length=550, null=True)


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(max_length=500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    participants = models.ManyToManyField(
        User, related_name='participants', blank=True)

    class Meta:
        ordering = ['-modified_at', 'created_at']

    def __str__(self):
        return self.name


class Messages(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    message = models.TextField(max_length=1000, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at', 'created_at']

    def __str__(self):
        return self.message[0:50]

app/templates/activity.html
{% extends 'base.html' %} {% block content %}
<main class="layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>Recent Activities</h3>
        </div>
      </div>

      <div class="activities-page layout__body">
        {% for message in room_activity %}

        <div class="activities__box">
          <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
              <div class="avatar avatar--small">
                <img src="{{message.user.profile.profile_picture.url}}" />
              </div>
              <p>
                @{{message.user}}
                <span>{{message.created_at|timesince}} ago</span>
              </p>
            </a>
            {% if request.user == message.user %}
            <div class="roomListRoom__actions">
              <a href="{% url 'delete-message' message.id %}">
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 32 32"
                >
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                  ></path>
                </svg>
              </a>
            </div>
            {% endif %}
          </div>
          <div class="activities__boxContent">
            <p>replied to post “<a href="{% url 'room' message.room.id %}">{{message.room}}</a>”</p>
            <div class="activities__boxRoomContent">{{message}}</div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</main>
{% endblock content %}

app/templates/activity_comp.html
<div class="activities">
  <div class="activities__header">
    <h2>Recent Activities</h2>
  </div>
  {% for message in room_activity %}

  <div class="activities__box">
    <div class="activities__boxHeader roomListRoom__header">
      <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="{{message.user.profile.profile_picture.url}}" />
        </div>
        <p>
          @{{message.user.username}}
          <span>{{message.created_at|timesince}} ago</span>
        </p>
      </a>
      {% if request.user == message.user %}
      <div class="roomListRoom__actions">
        <a href="{% url 'delete-message' message.id %}">
          <svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            viewBox="0 0 32 32"
          >
            <title>remove</title>
            <path
              d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
            ></path>
          </svg>
        </a>
      </div>
      {% endif %}
    </div>
    <div class="activities__boxContent">
      <p>replied to post “<a href="{% url 'room' message.room.id %}">{{message.room}}</a>”</p>
      <div class="activities__boxRoomContent">{{message}}</div>
    </div>
  </div>
  {% endfor %}
</div>

app/templates/alerts.html
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <label class="show-notification">
    <input type="checkbox" class="alertCheckbox" autocomplete="off" />
    <div class="alert {{message.tags}}">
      <span class="alertClose">X</span>
      <span class="alertText">{{message}} <br class="clear" /></span>
    </div>
  </label>
</ul>
{% endfor %} {% endif %}

app/templates/base.html
{% load static %}
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />

    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />

    <title>StudentCircle - Connect with student around the world!</title>
  </head>

  <body>
    {% include 'navbar.html' %} {% block content %} {% endblock content%}
    <!-- prettier-ignore -->
    {% include 'alerts.html'%}

    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

app/templates/delete.html
{% extends 'base.html' %} {% block content %}
<main class="delete-item layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <div>
          <h3 >Delete</h3> 
          </div>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="" method="POST">
          {% csrf_token %}
            <div class="delete-items form__group">
              <p>Are you sure you want to delete <h4>"{{obj}}"<h4> ?</p>
            </div>
          <div class="delete-items">

          <div class="for__group">
            <input class="btn btn--main" type="submit" value="Confirm" />
          </div>
          <div class="for__group">
            <a href="{{request.META.HTTP_REFERER}}" class="btn btn--main">Cancel</a>
          </div>

          <div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

app/templates/edit-user.html
{% extends 'base.html' %}
{% block content %}

    <main class="update-account layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'home' %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Edit your profile</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method="POST" enctype="multipart/form-data">
                      {% csrf_token %}
                        <div class="edit-form">
                            <div class="edit-element">
                                {% for field in p_form %}
                                <div class="form__group">
                                    <label for="{{field.label}}">{{field.label}}</label>
                                    {{field}}
                                </div>
                                {% endfor %}
                            </div>
                            <div class="edit-element">
                                {% for field in form %}
                                <div class="form__group">
                                    <label for="{{field.label}}">{{field.label}}</label>
                                    {{field}}
                                </div>
                                {% endfor %}
                                <div>
                                <img src="{{request.user.profile.profile_picture.url}}" alt="profile-image" style="width:200px">

                                </div>

                            </div>
                        </div>
                        <div class="form__action">
                            <a class="btn btn--dark" href="index.html">Cancel</a>
                            <button class="btn btn--main" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
      </div>
    </main>
    {% endblock content %}

app/templates/feed_comp.html
{% for room in rooms %}

<div class="roomListRoom">
  <div class="roomListRoom__header">
    <a href="{% url 'user-profile' room.host.id %}" class="roomListRoom__author">
      <div class="avatar avatar--small">
        <img src="{{room.host.profile.profile_picture.url}}" />
      </div>
      <span>@{{room.host.username}}</span>
    </a>
    <div class="roomListRoom__actions">
      <span>{{ room.created_at|timesince }} ago</span>
    </div>
  </div>
  <div class="roomListRoom__content">
    <a href="{% url 'room' room.id %}">{{room.name}}</a>
    <p>{{room.description}}</p>
  </div>
  <div class="roomListRoom__meta">
    <a href="{% url 'room' room.id %}" class="roomListRoom__joined">
      <svg
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        width="32"
        height="32"
        viewBox="0 0 32 32"
      >
        <title>user-group</title>
        <path
          d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
        ></path>
        <path
          d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
        ></path>
        <path
          d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
        ></path>
        <path
          d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
        ></path>
      </svg>
      {{room.participants.all.count}} Joined
    </a>
    <p class="roomListRoom__topic">{{room.topic.name}}</p>
  </div>
</div>
{% endfor %}

app/templates/forgot_pass.html
{% extends 'base.html' %} {% block content %}
<main class="auth layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Account Recovery</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Enter your email to send rest link</h2>

        <form class="form" action="" method="POST">
          <div class="login-center">
            {% csrf_token %}
            <div class="form__group">
              <label for="room_name">Email</label>
              <input id="username" name="email" type="text" placeholder="e.g. learners@gmail.com" />
            </div>
            <div>
              <button class="btn btn--main" type="submit">Send</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>

{% endblock content %}

app/templates/home.html
{% extends 'base.html' %} {% block content %}
<main class="layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include 'topic_comp.html' %}
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="mobile-menu">
        <form class="header__search" action="{% url 'home' %}" method="GET">
          <label>
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input name="q" placeholder="Search for posts" />
          </label>
        </form>
        <div class="mobile-menuItems">
          <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Browse Topics</a>
          <a class="btn btn--main btn--pill" href="{% url 'activity' %}">Recent Activities</a>
        </div>
      </div>
      <div class="roomList__header">
        <div>
          <h2>Student Room</h2>
          <p>{{room_count}} Rooms available</p>
        </div>
        <a class="btn btn--main" href="{% url 'create-room' %}">
          <svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            viewBox="0 0 32 32"
          >
            <title>add</title>
            <path
              d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
            ></path>
          </svg>
          Create Room
        </a>
      </div>
      {% include 'feed_comp.html' %}
    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'activity_comp.html' %}
    <!-- Activities End -->
  </div>
</main>
{% endblock content %}

app/templates/login_register.html
{% extends 'base.html' %} {% block content %}
<main class="auth layout">
  {% if page == 'login' %}
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Login</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Find your study partner</h2>

        <form class="form" action="" method="POST">
          <div class="login-center">
            {% csrf_token %}
            <div class="form__group">
              <label for="room_name">Email</label>
              <input id="username" name="email" type="text" placeholder="e.g. learners@gmail.com" />
            </div>
            <div class="form__group">
              <label for="password">Password</label>
              <input
                id="password"
                name="password"
                type="password"
                placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
              />
            </div>
            <div>
              <button class="btn btn--main" type="submit">
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 32 32"
                >
                  <title>lock</title>
                  <path
                    d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                  ></path>
                  <path
                    d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                  ></path>
                </svg>

                Login
              </button>
              <br />
              <a style="margin-top: 1rem" href="{% url 'forgot-password' %}">Forgot Password </a>
            </div>
          </div>
        </form>

        <div class="auth__action">
          <p>Haven't signed up yet?</p>
          <a href="{% url 'register' %}" class="btn btn--link">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Sign Up</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Find your study partner</h2>

        <form class="form" action="" method="POST">
          {% csrf_token %} {% for field in form %}
          <div class="form__group form__group">
            <label for="room_name">{{field.label}}</label>
            {{field}}
          </div>
          {% endfor %}

          <button class="btn btn--main" type="submit">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
              ></path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
              ></path>
            </svg>

            Sign Up
          </button>
        </form>

        <div class="auth__action">
          <p>Already signed ?</p>
          <a href="{% url 'login' %}" class="btn btn--link">Log In</a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</main>

{% endblock content %}

app/templates/reset_password.html
{% extends 'base.html' %} {% block content %}
<main class="auth layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Account Recovery</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Enter your email to send rest link</h2>

        <form class="form" action="" method="POST">
          <div class="login-center">
            {% csrf_token %}
            <div class="form__group">
              <label for="room_name">Password</label>
              <input id="password" name="password" type="password" placeholder="password..." />
            </div>
            <div class="form__group">
              <label for="room_name">Confirm Password</label>
              <input
                id="conf_password"
                name="conf_password"
                type="password"
                placeholder="password..."
              />
            </div>
            <div>
              <button class="btn btn--main" type="submit">Reset</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>

{% endblock content %}

app/templates/topic_comp.html
<div class="topics">
  <div class="topics__header">
    <h2>Browse Topics</h2>
  </div>
  <ul class="topics__list">
    <li>
      <a href="{% url 'home' %}" class="active">ALL<span>{{topics.count}}</span></a>
    </li>

    {% for topic in topics %}
    <li>
      <a href="{% url 'home' %}?q={{topic.name}}" class="active"
        >{{topic.name}} <span>{{topic.room_set.all.count}}</span></a
      >
    </li>
    {% endfor %}
  </ul>
  <a class="btn btn--link" href="{% url 'topics' %}">
    More
    <svg
      version="1.1"
      xmlns="http://www.w3.org/2000/svg"
      width="32"
      height="32"
      viewBox="0 0 32 32"
    >
      <title>chevron-down</title>
      <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
    </svg>
  </a>
</div>

app/templates/topics.html
{% extends 'base.html' %} {% block content %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>Browse Topics</h3>
        </div>
      </div>

      <div class="topics-page layout__body">
        <form class="header__search" action="" method="GET">
          <label>
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input name="q" placeholder="Search for posts" />
          </label>
        </form>

        <ul class="topics__list">
          <li>
            <a href="{% url 'topics' %}" class="active">All <span>{{topics.count}}</span></a>
          </li>
          {% for topic in topics %}
          <li>
            <a href="{% url 'home' %}?q={{topic.name}}" class="active"
              >{{topic.name}} <span>{{topic.room_set.all.count}}</span></a
            >
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</main>
{% endblock content %}